### ISSUE TITLE
a few polaris components not working

### ISSUE THREAD

**Issue by wflore19** [jaredkc/remix-shopify-polaris#1]
I found a few components like 'TextField' use Client side API's like `useState()` and `useCallback()` [here in the docs](https://polaris.shopify.com/components/selection-and-input/text-field?example=text-field-default), 

Does this mean I can't use these components out of the box w/ Remix?

**Comment by wflore19** [comment]
I got it to work the example in the docs, I'm confused how React API's like useState() and useCallback() can be used in a Route Component if it renders on the server...

**Comment by jaredkc** [comment]
@wflore19, in case it is still helpful. You can pass the data from the Remix Loader or Action as the default value for useState. 

```jsx
export default function Index() {
    const { serverValue } = useLoaderData<typeof loader>();
    
    const [value, setValue] = useState(serverValue || "");

    const handleChange = useCallback(
        (newValue: string) => setValue(newValue),
        [],
    );

     return (
        <TextField
            label="Store name"
            value={value}
            onChange={handleChange}
            autoComplete="off"
        />
    )
}
```
